# Generated by Django 3.2.4 on 2021-09-08 13:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_curso_datainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='datainicio',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 13, 45, 44, 684762, tzinfo=utc)),
        ),
    ]
